### PR TITLE
Adding image space documentation

### PR DESCRIPTION
**Pull request by SeanFitzgibbon**

### CODE REVIEW

**Comment by jcupitt** [comment]
Looks good to me.

**Comment by maxpietsch** [comment]
Thanks, Sean, looks good! I've added links to the atlases. Is the reference for the symmetric surface atlas correct?

**Review by maxpietsch — APPROVED** [review]

**Comment by SeanFitzgibbon** [comment]
>  Is the reference for the symmetric surface atlas correct?

No, that is the link for the asymmetric surface atlas. @ecr05 and/or @lzjwilliams should know the new link...

**Review by jcupitt — APPROVED** [review]

**Comment by SeanFitzgibbon** [comment]
I removed the symmetric atlas link for now.  We can add in back in when a link is available.

**Pull request merged**
